[pytest]
filterwarnings =
    ignore:.*allowed_objects.*:langchain_core._api.deprecation.LangChainPendingDeprecationWarning
    ignore:.*allowed_objects.*:UserWarning
    ignore::DeprecationWarning:langgraph.*
    ignore::langchain_core._api.deprecation.LangChainPendingDeprecationWarning
